<html lang="en">

<head>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.min.css">
</head>

<body>
    <h2>Hello visitor!</h2>

    <form method="post">

        <h1>Add your details</h1>
        <label>Name</label>
        <input type="text" name="name" placeholder="Michael" required value="">

        

        <input type="submit" value="Add">
    </form>

</body>
</html>